---
title: "NLREC"
output: pdf_document
---

```{r}
EffortinTime <- function(minsurvey,plotradius,plotheight){
        totalhr <- minsurvey/60
        plotvolume <- pi*plotheight*plotradius^2
        SmpHrKm <<- totalhr*plotvolume
}

Hazard <- function(rotorradius,height,numberofturbine,active){
        hazardspace <<- pi*height*rotorradius^2
        ExpFac <<- numberofturbine*hazardspace*active
}

Exposure <- function(flightmin){
        library(MASS)
        birdexp <<- flightmin/SmpHrKm
        y <- fitdistr(birdexp,"gamma")
        aPriExp <<- unlist(y$estimate[1])
        bPriExp <<- unlist(y$estimate[2])
}

simFatal <- function(BMin=-1, Fatal=-1, SmpHrKm, ExpFac, aPriExp=1,
                     bPriExp=1,aPriCPr=1, bPriCPr=1){
        
        # BMin:     observed number of bird minutes
        # Fatal:    annual avian fatalities on an operational wind facility
        # SmpHrKm:  total time and area surveyed for bird minutes
        # ExpFac:   expansion factor
        # aPriExp:  alpha parameter for the prior on lambda
        # bPriExp:  beta parameter for the prior on lambda
        # aPriCPr:  alpha parameter for the prior on C
        # bPriCPr:  beta parameter for the prior on C
        # The default of a negative value for BMin or Fatal indicates that no data were collected for those model inputs
        
        require(rv)
        
        # Update the exposure prior 
        if(BMin>=0){
                aPostExp <- aPriExp + BMin
                bPostExp <- bPriExp + SmpHrKm
        }else{
                aPostExp <- aPriExp
                bPostExp <- bPriExp}
        
        Exp <- rvgamma(n=1, aPostExp, bPostExp)
        
        # Update the collisions prior
        if(Fatal>=0){
                aPostCPr <- aPriCPr + Fatal
                bPostCPr <- ((rvmean(Exp) * ExpFac) - Fatal) + bPriCPr
        }else{
                aPostCPr <- aPriCPr
                bPostCPr <- bPriCPr}
        
        CPr <- rvbeta(n=1, aPostCPr, bPostCPr)
        
        Fatalities             <- ExpFac * Exp * CPr
        attr(Fatalities,"Exp") <- c(Mean=rvmean(Exp), SD=rvsd(Exp))
        attr(Fatalities,"CPr") <- c(Mean=rvmean(CPr), SD=rvsd(CPr))
        
        return(Fatalities)}

Hazard(0.049,0.101,27,4460.147)
EffortinTime(2300,0.2,0.1)
flightmin <- c(1/15,0.2)
Exposure(flightmin)
simFatal(BMin=4/15,SmpHrKm = SmpHrKm,ExpFac=ExpFac,aPriExp = aPriExp,bPriExp = bPriExp)

set.seed(100)
x <- rgamma(1000,aPriExp,bPriExp)
plot(x,dgamma(x,shape=3.63,rate=13.1),main="Exposure Rate", ylab="density",xlab="bird exposure", type="p",col="dark red",cex=0.3,pch=16)
lines(x,dgamma(x,shape=1,rate=1),type="p",col="spring green",cex=0.3,pch=16)
lines(x,dgamma(x,shape=3.897,rate=13.58171),type="p",col="blue",cex=0.3,pch=16)
```


Luzon Hornbill

```{r}
EffortinTime(2300,0.2,0.1)
Hazard(0.049,0.101,27,4460.147)
flightmin <- c(0.05,1/12,1/30)
Exposure(flightmin)
simFatal(BMin=1/6,SmpHrKm = SmpHrKm,ExpFac = ExpFac,aPriExp = aPriExp,bPriExp = bPriExp)
```

```{r}
flightmin <- c(7/60,3/20,1/30,1/30,0.05,0.45,0.15,0.15,0.3)
Exposure(flightmin)
simFatal(BMin=43/30,SmpHrKm = SmpHrKm,ExpFac = ExpFac,aPriExp = aPriExp,bPriExp = bPriExp)
```